language: node_js
node_js:
  - "8"
  - "10"
  - "12"
env:
  - CXX=g++-4.8
before_install: "sudo apt-get update && sudo apt-get install -y g++-4.8 libcairo2-dev libjpeg8-dev libgif-dev optipng pngcrush pngquant libpango1.0-dev graphicsmagick libjpeg-turbo-progs inkscape gifsicle"
script: "npm run-script travis"
after_success: '<coverage/lcov.info ./node_modules/coveralls/bin/coveralls.js'
